In [1]:
!pip install opencv-python

   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/38.8 MB 284.4 kB/s eta 0:02:17
   ---------------------------------------- 0.1/38.8 MB 284.4 kB/s eta 0:02:17
   ---------------------------------------- 0.1/38.8 MB 284.4 kB/s eta 0:02:17
   ---------------------------------------- 0.1/38.8 MB 284.4 kB/s eta 0:02:17
   ---------------------------------------- 0.1/38.8 MB 284.4 kB/s eta 0:02:17
   ---------------------------------------- 0

In [1]:
import cv2
import numpy as np

#### 1) cv2.imread()

In [3]:
img = cv2.imread(r"C:\Users\91912\Downloads\peakpx.jpg")

In [9]:
type(img)

numpy.ndarray

In [11]:
img.shape

(1200, 1920, 3)

In [13]:
img

array([[[20,  6,  0],
        [21,  7,  1],
        [22,  8,  2],
        ...,
        [ 5,  1,  0],
        [ 5,  1,  0],
        [ 5,  1,  0]],

       [[21,  7,  1],
        [21,  7,  1],
        [22,  8,  2],
        ...,
        [ 5,  1,  0],
        [ 5,  1,  0],
        [ 5,  1,  0]],

       [[21,  7,  1],
        [21,  7,  1],
        [22,  8,  2],
        ...,
        [ 5,  1,  0],
        [ 5,  1,  0],
        [ 5,  1,  0]],

       ...,

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]], dtype=uint8)

In [15]:
img.dtype

dtype('uint8')

In [17]:
img1 = cv2.imread(r"C:\Users\91912\Downloads\peakpx.jpg",flags = 0)

In [19]:
type(img1)

numpy.ndarray

In [21]:
img1.shape

(1200, 1920)

In [23]:
img1.dtype

dtype('uint8')

In [25]:
img1

array([[6, 7, 8, ..., 1, 1, 1],
       [7, 7, 8, ..., 1, 1, 1],
       [7, 7, 8, ..., 1, 1, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

#### Creating black and white images using arrays.

In [5]:
white_img = np.full((300,300),255,dtype = np.uint8)
black_img = np.zeros((300,300),dtype=np.uint8)

#### 2) cv2.imshow()

In [7]:
cv2.imshow("grey",white_img)
cv2.imshow("black",black_img)

cv2.waitKey(0)  # 0 and no values means infinite delay i.e pop-up window closes when we click on "X" mark 

cv2.destroyAllWindows()

#### Task

In [13]:
b = np.full((300,300),255,dtype = np.uint8)
g = np.zeros((300,300),dtype = np.uint8)
r = np.zeros((300,300),dtype = np.uint8)

color_img = cv2.merge([b,g,r])

In [21]:
r = np.full((300,300),255,dtype = np.uint8)
g = np.zeros((300,300),dtype = np.uint8)
b = np.zeros((300,300),dtype = np.uint8)

color_img1 = cv2.merge([b,g,r])

In [23]:
g = np.full((300,300),255,dtype = np.uint8)
b = np.zeros((300,300),dtype = np.uint8)
r = np.zeros((300,300),dtype = np.uint8)

color_img2 = cv2.merge([b,g,r])

In [25]:
cv2.imshow("Blue",color_img)
cv2.imshow("Red",color_img1)
cv2.imshow("Green",color_img2)

cv2.waitKey(0)

cv2.destroyAllWindows()

### Converting Images to tabular structure

In [1]:
pip install kagglehub

   ---------------------------------------- 0.0/43.0 kB ? eta -:--:--
   --------- ------------------------------ 10.2/43.0 kB ? eta -:--:--
   --------- ------------------------------ 10.2/43.0 kB ? eta -:--:--
   --------- ------------------------------ 10.2/43.0 kB ? eta -:--:--
   --------- ------------------------------ 10.2/43.0 kB ? eta -:--:--
   --------- ------------------------------ 10.2/43.0 kB ? eta -:--:--
   --------- ------------------------------ 10.2/43.0 kB ? eta -:--:--
   --------- ------------------------------ 10.2/43.0 kB ? eta -:--:--
   -------------------------------------- - 41.0/43.0 kB 89.6 kB/s eta 0:00:01
   ---------------------------------------- 43.0/43.0 kB 87.4 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [3]:
import kagglehub

In [9]:
path = kagglehub.dataset_download("rahmasleam/flowers-dataset")

100%|███████████████████████████████████████████████████████████████████████████████| 219M/219M [02:34<00:00, 1.48MB/s]

Extracting files...


In [11]:
path

'C:\\Users\\91912\\.cache\\kagglehub\\datasets\\rahmasleam\\flowers-dataset\\versions\\1'

In [15]:
import os

In [17]:
folders = os.listdir(r"C:\Users\91912\Downloads\flower_photos")
folders

['daisy', 'dandelion', 'roses', 'sunflowers', 'tulips']

In [47]:
os.listdir(r"C:\Users\91912\Downloads\flower_photos\tulips")

['100930342_92e8746431_n.jpg',
 '10094729603_eeca3f2cb6.jpg',
 '10094731133_94a942463c.jpg',
 '10128546863_8de70c610d.jpg',
 '10163955604_ae0b830975_n.jpg',
 '10164073235_f29931d91e.jpg',
 '10686568196_b1915544a8.jpg',
 '107693873_86021ac4ea_n.jpg',
 '10791227_7168491604.jpg',
 '10995953955_089572caf0.jpg',
 '110147301_ad921e2828.jpg',
 '112334842_3ecf7585dd.jpg',
 '112428665_d8f3632f36_n.jpg',
 '112428919_f0c5ad7d9d_n.jpg',
 '112650879_82adc2cc04_n.jpg',
 '112651128_7b5d39a346_m.jpg',
 '112951022_4892b1348b_n.jpg',
 '112951086_150a59d499_n.jpg',
 '113291410_1bdc718ed8_n.jpg',
 '113902743_8f537f769b_n.jpg',
 '113960470_38fab8f2fb_m.jpg',
 '11441893003_ab83672800.jpg',
 '11614202956_1dcf1c96a1.jpg',
 '116343334_9cb4acdc57_n.jpg',
 '11746080_963537acdc.jpg',
 '11746276_de3dec8201.jpg',
 '11746367_d23a35b085_n.jpg',
 '11746452_5bc1749a36.jpg',
 '11746548_26b3256922_n.jpg',
 '12024561754_ce9667e4dc_n.jpg',
 '12025038686_7f10811d4b_n.jpg',
 '12025042086_78bafc0eb6_n.jpg',
 '12163418275_bd6a

In [19]:
features = []
class_labels = []
for folder in folders:
    for images in os.listdir(r"C:\Users\91912\Downloads\flower_photos\{}".format(folder)):
        img = cv2.imread(r"C:\Users\91912\Downloads\flower_photos\{}\{}".format(folder,images),0)
        img = cv2.resize(img,(50,50)) # resize the image
        img = img.flatten()  # Falttening array
        features.append(img)  
        class_labels.append(folder)

In [27]:
len(features)

3670

In [29]:
len(class_labels)

3670

In [31]:
import pandas as pd

In [33]:
df = pd.DataFrame(features)

In [37]:
df["Class Labels"] = class_labels

In [39]:
df

0    1    2    3    4    5    6    7    8    9  ...  2491  2492  2493  \
0     143  149  160  169  167  167  145  144  144  159  ...   174   168   149   
1     224  222  216  232  228   75   85   80  182  185  ...   116   107   110   
2     108   81   97   84  102  120  108  106  140  128  ...    44    27    26   
3      26   25   26   29   32   35   37   38   38   40  ...    16    15    16   
4      20   21   36   45   46   45   40   42   37   56  ...    42    48    42   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   
3665  212  189  186  212   47   82  116  131   82   79  ...   103   114    40   
3666  135  126  129  131  119  141  135  128  132  136  ...    53    60    58   
3667   88   72   78   97   57   77   91   79   46   77  ...    71    81    89   
3668  157  189  169  132  174  162  185  174  122  160  ...   152   193    74   
3669   49   62  118  122   75  164  127   98   74   78  ...   146    80    45   

      2494  2495  2496  2497  2498  2499  Class Labels  
0      134   128   137   137   131   127         daisy  
1      108   156   169   141   125   172         daisy  
2       26    27    27    31    36    40         daisy  
3       21    18    24    16    20    23         daisy  
4       26    25    31    39    27    35         daisy  
...    ...   ...   ...   ...   ...   ...           ...  
3665     7    30    30    86   194   215        tulips  
3666    54    41    48    84   132   120        tulips  
3667    91    91    87   103    80    80        tulips  
3668    23    18     8    12    19    45        tulips  
3669    63    47    91    56    76    57        tulips  

[3670 rows x 2501 columns]

In [41]:
df.shape

(3670, 2501)

In [45]:
df.info()   # df = df.astype(np.unit8)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3670 entries, 0 to 3669
Columns: 2501 entries, 0 to Class Labels
dtypes: object(1), uint8(2500)
memory usage: 8.8+ MB


#### Task - Showing a image in b,g,r shades

In [13]:
img = cv2.imread(r"C:\Users\91912\Downloads\flower_photos\tulips\38287568_627de6ca20.jpg")

In [15]:
img

array([[[175, 142, 116],
        [176, 143, 117],
        [177, 144, 118],
        ...,
        [167, 138, 111],
        [167, 138, 111],
        [167, 138, 111]],

       [[174, 143, 118],
        [174, 143, 118],
        [177, 143, 119],
        ...,
        [167, 138, 111],
        [167, 138, 111],
        [167, 138, 111]],

       [[174, 143, 120],
        [174, 143, 120],
        [176, 144, 121],
        ...,
        [168, 139, 112],
        [168, 139, 112],
        [168, 139, 112]],

       ...,

       [[  3,  30,  20],
        [  3,  27,  15],
        [ 10,  28,  15],
        ...,
        [  0,  10,   0],
        [  0,  15,   4],
        [  3,  23,  11]],

       [[  5,  30,  20],
        [  5,  27,  15],
        [  9,  27,  14],
        ...,
        [  0,  12,   1],
        [  6,  26,  14],
        [ 18,  42,  30]],

       [[  4,  29,  19],
        [  4,  26,  14],
        [  7,  25,  12],
        ...,
        [  0,  17,   6],
        [ 17,  41,  29],
        [ 40,  68,  55]]

In [17]:
img.shape

(333, 500, 3)

In [19]:
b,g,r = cv2.split(img)

In [7]:
zeroes = np.zeros((333,500),dtype = np.uint8)

In [21]:
blue_channel = cv2.merge([b,zeroes,zeroes])
green_channel = cv2.merge([zeroes,g,zeroes])
red_channel = cv2.merge([zeroes,zeroes,r])

In [24]:
cv2.imshow("Blue_Channel",blue_channel)
cv2.imshow("Green_Channel",green_channel)
cv2.imshow("Red_Channel",red_channel)
cv2.imshow("Orginal_img",cv2.merge([b,g,r]))

cv2.waitKey(0)

cv2.destroyAllWindows()

#### 3) cv2.imwrite()

In [43]:
white_img = np.full((100,100),200,dtype = np.uint8)

In [50]:
cv2.imwrite(r"C:\Users\91912\Downloads\grey_image.jpg",white_img)  # extension is very very important

True