In [1]:
pip install opencv-python


  Using cached opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl.metadata (20 kB)
   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.8 MB 435.7 kB/s eta 0:01:30
   ---------------------------------------- 0.0/38.8 MB 435.7 kB/s eta 0:01:30
   ---------------------------------------- 0.0/38.8 MB 435.7 kB/s eta 0:01:30
   ---------------------------------------- 0.1/38.8 MB 218.8 kB/s eta 0:02:58
   ---------------------------------------- 0.1/38.8 MB 218.8 kB/s eta 0:02:58
   ---------------------------------------- 0.1/38.8 MB 218.8 kB/s eta 0:02:58
   ---------------------------------------- 0.1/38.8 MB 218.8 kB/s eta 0:02:58
   ---------------------------------------- 0.1/38.8 MB 218.8 kB/s eta 0:02:58
   ---------------------------------------- 0.1/38.8 MB 145.6 kB/s eta 0:04:27
   ---------------------------------------- 0.1/38.8 MB 145.6 kB/s e

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\syam0\Downloads\Saniya Mastan\Lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\syam0\Downloads\Saniya Mastan\Lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\syam0\Downloads\Saniya Mastan\Lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\syam0\Downloads\Saniya Mastan\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syam0\Downloads\Saniya Mastan\Lib\http\client.py", line 479, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\syam0\Downloads\Saniya Mastan\L

   ------------------------ --------------- 23.8/38.8 MB 416.5 kB/s eta 0:00:37
   ------------------------ --------------- 23.8/38.8 MB 416.5 kB/s eta 0:00:37
   ------------------------ --------------- 23.8/38.8 MB 416.5 kB/s eta 0:00:37
   ------------------------ --------------- 23.8/38.8 MB 416.5 kB/s eta 0:00:37
   ------------------------ --------------- 23.8/38.8 MB 416.5 kB/s eta 0:00:37
   ------------------------ --------------- 23.8/38.8 MB 416.5 kB/s eta 0:00:37
   ------------------------ --------------- 23.8/38.8 MB 416.5 kB/s eta 0:00:37
   ------------------------ --------------- 23.8/38.8 MB 416.5 kB/s eta 0:00:37
   ------------------------ --------------- 23.8/38.8 MB 416.5 kB/s eta 0:00:37
   ------------------------ --------------- 23.8/38.8 MB 416.5 kB/s eta 0:00:37
   ------------------------ --------------- 23.8/38.8 MB 416.5 kB/s eta 0:00:37
   ------------------------ --------------- 23.8/38.8 MB 416.5 kB/s eta 0:00:37
   ------------------------ ------------

In [1]:
import cv2

In [3]:
import numpy as np

### White and Black Image

In [5]:
white_img = np.full((500,500),255,dtype=np.uint8)
black_img = np.zeros((500,500),dtype=np.uint8)

### To display the array into Image format

In [7]:
cv2.imshow("white",white_img)   ## white is window or pop-up wind name followed by array name
cv2.imshow("black",black_img)   

cv2.waitKey(1000) #### waitKey is used to specify the time till wat time the wind should be displayed

cv2.destroyAllWindows() ## top destroy from the ram

## Color Images

#### Red color image

In [1]:
b = np.zeros((500,500),dtype=np.uint8)
g = np.zeros((500,500),dtype=np.uint8)
r = np.full((500,500),255,dtype=np.uint8)

color_img1=cv2.merge([b,g,r])   ### Merging the three channels into 3d array

NameError: name 'np' is not defined

#### Blue color image

In [13]:
b = np.full((500,500),255,dtype=np.uint8)
g = np.zeros((500,500),dtype=np.uint8)
r = np.zeros((500,500),dtype=np.uint8)

color_img2=cv2.merge([b,g,r])

#### Green color image

In [15]:
b = np.zeros((500,500),dtype=np.uint8)
g = np.full((500,500),255,dtype=np.uint8)
r = np.zeros((500,500),dtype=np.uint8)

color_img3=cv2.merge([b,g,r])

#### Displaying the different color arrays into color image formats

In [ ]:
cv2.imshow("red",color_img1)
cv2.imshow("blue",color_img2)
cv2.imshow("green",color_img3)

cv2.waitKey(0)

cv2.destroyAllWindows()

### Converting Grid like structure to tabular Format

In [1]:
pip install kagglehub

   ---------------------------------------- 0.0/43.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/43.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/43.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/43.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/43.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/43.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/43.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/43.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/43.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/43.0 kB ? eta -:--:--
   ---------------------------------------- 43.0/43.0 kB 2.0 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [1]:
import kagglehub

In [3]:
# Download latest version
path = kagglehub.dataset_download("rahmasleam/flowers-dataset")

100%|███████████████████████████████████████████████████████████████████████████████| 219M/219M [00:27<00:00, 8.44MB/s]

Extracting files...


In [4]:
path

'C:\\Users\\syam0\\.cache\\kagglehub\\datasets\\rahmasleam\\flowers-dataset\\versions\\1'

In [1]:
import os
import cv2

In [3]:
folders = os.listdir(r"C:\Users\syam0\.cache\kagglehub\datasets\rahmasleam\flowers-dataset\versions\1\flower_photos")
folders

['daisy', 'dandelion', 'roses', 'sunflowers', 'tulips']

In [5]:
features=[]
class_labels=[]
for folder in folders:
    for images in os.listdir(r"C:\Users\syam0\.cache\kagglehub\datasets\rahmasleam\flowers-dataset\versions\1\flower_photos\{}".format(folder)):
        img=cv2.imread(r"C:\Users\syam0\.cache\kagglehub\datasets\rahmasleam\flowers-dataset\versions\1\flower_photos\{}\{}".format(folder,images),0)
        img=cv2.resize(img,(50,50))
        img = img.flatten()
        features.append(img)
        class_labels.append(folder)

In [6]:
len(features)

3670

In [7]:
len(class_labels)

3670

In [3]:
import pandas as pd

In [13]:
final_data= pd.DataFrame(features)
final_data

0     1     2     3     4     5     6     7     8     9     ...  2490  \
0      143   149   160   169   167   167   145   144   144   159  ...   171   
1      224   222   216   232   228    75    85    80   182   185  ...   120   
2      108    81    97    84   102   120   108   106   140   128  ...    38   
3       26    25    26    29    32    35    37    38    38    40  ...    18   
4       20    21    36    45    46    45    40    42    37    56  ...    26   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
3665   212   189   186   212    47    82   116   131    82    79  ...    83   
3666   135   126   129   131   119   141   135   128   132   136  ...    48   
3667    88    72    78    97    57    77    91    79    46    77  ...    83   
3668   157   189   169   132   174   162   185   174   122   160  ...    57   
3669    49    62   118   122    75   164   127    98    74    78  ...    98   

      2491  2492  2493  2494  2495  2496  2497  2498  2499  
0      174   168   149   134   128   137   137   131   127  
1      116   107   110   108   156   169   141   125   172  
2       44    27    26    26    27    27    31    36    40  
3       16    15    16    21    18    24    16    20    23  
4       42    48    42    26    25    31    39    27    35  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
3665   103   114    40     7    30    30    86   194   215  
3666    53    60    58    54    41    48    84   132   120  
3667    71    81    89    91    91    87   103    80    80  
3668   152   193    74    23    18     8    12    19    45  
3669   146    80    45    63    47    91    56    76    57  

[3670 rows x 2500 columns]

In [29]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3670 entries, 0 to 3669
Columns: 2500 entries, 0 to 2499
dtypes: int8(2500)
memory usage: 8.8 MB


In [5]:
import numpy as  np

In [37]:
final_data = final_data.astype(np.uint8)

In [39]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3670 entries, 0 to 3669
Columns: 2500 entries, 0 to 2499
dtypes: uint8(2500)
memory usage: 8.8 MB


In [41]:
final_data.shape

(3670, 2500)

In [45]:
img1 =cv2.imread(r"C:\Users\syam0\.cache\kagglehub\datasets\rahmasleam\flowers-dataset\versions\1\flower_photos\daisy\5547758_eea9edfd54_n.jpg",0)

In [47]:
img1

array([[112, 106, 102, ...,  48,  50,  52],
       [128, 121, 117, ...,  49,  50,  52],
       [136, 129, 124, ...,  51,  51,  53],
       ...,
       [250, 251, 252, ...,  21,  20,  19],
       [248, 250, 250, ...,  23,  22,  21],
       [251, 252, 249, ...,  25,  25,  24]], dtype=uint8)

In [49]:
img1.shape

(232, 320)

In [51]:
img1 = cv2.resize(img1,(50,50))

In [53]:
img1

array([[120,  81,  49, ...,  55,  51,  51],
       [161, 125,  90, ...,  59,  56,  59],
       [168, 156, 132, ...,  60,  67,  77],
       ...,
       [251, 250, 244, ...,  37,  38,  38],
       [250, 253, 242, ...,  31,  30,  22],
       [251, 231, 210, ...,  22,  20,  21]], dtype=uint8)

In [55]:
img1.shape

(50, 50)

In [59]:
img1 = img1.flatten()
img1

array([120,  81,  49, ...,  22,  20,  21], dtype=uint8)

In [71]:
white_img=np.full((400,500),255,dtype=np.uint8)

In [75]:
cv2.imwrite(r"C:\Users\syam0\.cache\kagglehub\datasets\rahmasleam\flowers-dataset\versions\1\flower_photos\white.jpg",white_img)

True

In [7]:
img = cv2.imread(r"C:\Users\syam0\.cache\kagglehub\datasets\rahmasleam\flowers-dataset\versions\1\flower_photos\tulips\54895006_55b49052dc.jpg")

In [9]:
img

array([[[205, 147, 111],
        [207, 149, 113],
        [206, 150, 115],
        ...,
        [214, 175, 143],
        [215, 176, 144],
        [214, 174, 145]],

       [[203, 148, 109],
        [205, 150, 111],
        [205, 150, 113],
        ...,
        [214, 173, 140],
        [212, 171, 138],
        [213, 172, 139]],

       [[205, 151, 110],
        [204, 152, 112],
        [203, 151, 111],
        ...,
        [216, 172, 135],
        [215, 171, 134],
        [216, 173, 134]],

       ...,

       [[  7,  43,  29],
        [  0,  30,  14],
        [  5,  37,  20],
        ...,
        [ 48, 137, 118],
        [ 56, 141, 126],
        [ 70, 152, 139]],

       [[  3,  39,  23],
        [  0,  33,  16],
        [  2,  32,  13],
        ...,
        [ 45, 136, 115],
        [ 45, 134, 115],
        [ 54, 143, 124]],

       [[  3,  36,  21],
        [  2,  34,  17],
        [  0,  28,   9],
        ...,
        [ 52, 142, 123],
        [ 49, 138, 119],
        [ 50, 140, 121]]

In [11]:
img.shape

(333, 500, 3)

In [13]:
img.shape[:-1]

(333, 500)

In [15]:
b,g,r =cv2.split(img)


In [17]:
zeros = np.zeros(img.shape[:-1],dtype = np.uint8)

In [19]:
blue_channel = cv2.merge([b,zeros,zeros])
green_channel = cv2.merge([zeros,g,zeros])
red_channel = cv2.merge([zeros,zeros,r])

In [ ]:
cv2.imshow("blue_channel",blue_channel)
cv2.imshow("green_channel",green_channel)
cv2.imshow("red_channel",red_channel)
cv2.imshow("or_image",cv2.merge([b,g,r]))

cv2.waitKey(0)

cv2.destroyAllWindows()