In [11]:
import numpy as np
import cv2
import os

In [13]:
img =cv2.imread(r"C:\Users\syam0\Downloads\LionHorse\Lion\Lion4.jpg")

In [9]:
img.shape

(360, 640, 3)

### Creating translation matrix

In [11]:
## translation

In [27]:
# translation matrix
tx = 50
ty = 50
t_img = np.array([[1,0,tx],[0,1,ty]],dtype=np.float32)
t_img = cv2.warpAffine(img,t_img,(640,360))

In [21]:
t_img

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 34, 161, 176],
        [ 35, 163, 176],
        [ 35, 163, 174]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 34, 159, 173],
        [ 34, 162, 173],
        [ 36, 165, 174]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 33, 159, 170],
        [ 32, 161, 170],
        [ 35, 165, 172]]

In [25]:
cv2.imshow("org_img",img)
cv2.imshow("t_img",t_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Adding borderMode

In [33]:
# translation matrix
tx = 50
ty = 50
t_img = np.array([[1,0,tx],[0,1,ty]],dtype=np.float32)

t_img1 = cv2.warpAffine(img,t_img,(640,360),borderMode=cv2.BORDER_CONSTANT,borderValue=(0,0,255))
t_img2 = cv2.warpAffine(img,t_img,(640,360),borderMode=cv2.BORDER_REFLECT)

In [41]:
cv2.imshow("org_img",img)
cv2.imshow("t_img1",t_img1)
cv2.imshow("t_img2",t_img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Rotation 

#### creating rotation matrix

In [47]:
img.shape

(360, 640, 3)

In [49]:
360/2

180.0

In [51]:
640/2

320.0

In [63]:
r_m = cv2.getRotationMatrix2D((180,320),-90,1)  #--- here 180 and 320 is the center pixel

In [65]:
r_m

array([[ 6.123234e-17, -1.000000e+00,  5.000000e+02],
       [ 1.000000e+00,  6.123234e-17,  1.400000e+02]])

In [67]:
rot_img = cv2.warpAffine(img,r_m,(640,360))

In [69]:
cv2.imshow("org_img",img)
cv2.imshow("rot_img",rot_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### here the pixel is the starting pixel i.e 0,0 and angel is 10 . and 1 is the same img size no zoom in and zoom out

In [71]:
r_m = cv2.getRotationMatrix2D((0,0),10,1)

In [73]:
r_m

array([[ 0.98480775,  0.17364818,  0.        ],
       [-0.17364818,  0.98480775,  0.        ]])

#### warpAffine has total control on the pixels and the angles i.e on transformation

In [75]:
rot_img1 = cv2.warpAffine(img,r_m,(640,360))

In [77]:
cv2.imshow("org_img",img)
cv2.imshow("rot_img",rot_img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### For direct rotation cv2 has the function i.e rotate

In [83]:
img1 = cv2.rotate(img,cv2.ROTATE_180)
img2 = cv2.rotate(img,cv2.ROTATE_90_CLOCKWISE)
img3 = cv2.rotate(img,cv2.ROTATE_90_COUNTERCLOCKWISE)

cv2.imshow("org_img",img)
cv2.imshow("rot_img1",img1)
cv2.imshow("rot_img2",img2)
cv2.imshow("rot_img3",img3)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Scaling --  zoom in or zoom out

In [26]:
sx = 2
sy =2
tx = 10
ty = 10
sc_m = np.array([[sx,0,tx],[0,sy,ty]],dtype = np.float32)

In [28]:
sc_m

array([[ 2.,  0., 10.],
       [ 0.,  2., 10.]], dtype=float32)

In [30]:
scal_img = cv2.warpAffine(img,sc_m,(3*640,3*360))

cv2.imshow("org_img",img)
cv2.imshow("scal_img",scal_img)
cv2.waitKey(10000)
cv2.destroyAllWindows()

#### directly with resize also we can perform zoomin and zoomout

In [12]:

cv2.imshow("org_img",cv2.resize(img,(500,500)))
cv2.imshow("scal_img",cv2.resize(scal_img,(50,50)))
cv2.waitKey(0)
cv2.destroyAllWindows()

#### functions of cv2 to zoomin and zoomout

In [15]:
zoom_out = cv2.pyrDown(img)
zoom_in = cv2.pyrUp(img)

In [ ]:
cv2.imshow("org_img",zoom_out)
cv2.imshow("scal_img",zoom_in)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Sheering

In [ ]:
shx = 1
shy =1
tx = 0
ty = 0
shx_m =np.array([[1,shx,tx],[shy,1,ty]],dtype =np.float32)


In [ ]:
shx_img=cv2.warpAffine(img,shx_m,(640,360))
cv2.imshow("org_img",img)
cv2.imshow("sh_img",shx_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Cropping

In [58]:
img= cv2.imread(r"C:\Users\syam0\Downloads\Saniya Mastan\catttt.jpg")

In [60]:
img.shape

(224, 225, 3)

In [66]:
crp_img = img[29:91,30:93]

In [68]:
cv2.imshow("org_img",img)
cv2.imshow("crp_img",crp_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [70]:
crp_img1 = img[1:48,112:163]

In [72]:
cv2.imshow("org_img",img)
cv2.imshow("crp_img1",crp_img1)
cv2.waitKey(0)
cv2.destroyAllWindows()